"""
KALI PENTEST PLATFORM v2 — MongoDB Client
All database operations. Uses Motor (async MongoDB driver).

Collections:
  sessions, findings, tool_outputs, agent_logs,
  shell_sessions, flags, attack_graph_nodes,
  attack_graph_edges, osint_results

MongoDB must be running: sudo systemctl start mongod
Default: mongodb://localhost:27017/kali_pentest
"""

import asyncio
from datetime import datetime
from typing import Optional, List, Dict, Any
from bson import ObjectId
from bson.errors import InvalidId
import motor.motor_asyncio
from pymongo import ASCENDING, DESCENDING, IndexModel

from db.schemas import (
    AttackPhase, AgentName, AgentStatus, FindingSeverity,
    SessionStatus, SessionCreate
)

# ─── Connection ────────────────────────────────────────────

MONGO_URI = "mongodb://localhost:27017"
DB_NAME   = "kali_pentest"

# Motor async client (initialized in setup())
_client:      Optional[motor.motor_asyncio.AsyncIOMotorClient]  = None
_db:          Optional[motor.motor_asyncio.AsyncIOMotorDatabase] = None
_db_instance: Optional[motor.motor_asyncio.AsyncIOMotorDatabase] = None  # Phase 3 alias


def get_db() -> motor.motor_asyncio.AsyncIOMotorDatabase:
    """Return database handle. Must call setup() first."""
    if _db is None:
        raise RuntimeError("MongoDB not initialized. Call await setup() first.")
    return _db


async def setup(uri: str = MONGO_URI, db_name: str = DB_NAME):
    """Initialize MongoDB connection and create indexes."""
    global _client, _db, _db_instance
    _client      = motor.motor_asyncio.AsyncIOMotorClient(uri)
    _db          = _client[db_name]
    _db_instance = _db  # Phase 3 alias
    await _create_indexes()
    print(f"[DB] Connected to MongoDB: {uri}/{db_name}")


async def teardown():
    """Close MongoDB connection."""
    global _client, _db, _db_instance
    if _client:
        _client.close()
        _db = None
        _db_instance = None
        print("[DB] MongoDB connection closed.")


async def _create_indexes():
    """Create indexes for efficient queries."""
    db = get_db()
    # sessions
    await db.sessions.create_index([("status", ASCENDING)])
    await db.sessions.create_index([("started_at", DESCENDING)])
    # findings
    await db.findings.create_index([("session_id", ASCENDING), ("severity", ASCENDING)])
    await db.findings.create_index([("session_id", ASCENDING), ("phase", ASCENDING)])
    await db.findings.create_index([("cves", ASCENDING)])
    # tool_outputs
    await db.tool_outputs.create_index([("session_id", ASCENDING), ("started_at", DESCENDING)])
    await db.tool_outputs.create_index([("session_id", ASCENDING), ("agent", ASCENDING)])
    # agent_logs
    await db.agent_logs.create_index([("session_id", ASCENDING), ("timestamp", DESCENDING)])
    await db.agent_logs.create_index([("session_id", ASCENDING), ("agent", ASCENDING)])
    # shell_sessions
    await db.shell_sessions.create_index([("session_id", ASCENDING), ("active", ASCENDING)])
    # flags
    await db.flags.create_index([("session_id", ASCENDING)])
    # attack graph
    await db.attack_graph_nodes.create_index([("session_id", ASCENDING)])
    await db.attack_graph_edges.create_index([("session_id", ASCENDING)])
    # osint
    await db.osint_results.create_index([("session_id", ASCENDING), ("relevance_score", DESCENDING)])
    # payloads (Phase 3)
    await db.payloads.create_index([("session_id", ASCENDING)])
    await db.payloads.create_index([("generated_at", DESCENDING)])
    # attack_tree — attack plans generated by planner agent
    await db.attack_tree.create_index([("session_id", ASCENDING), ("created_at", DESCENDING)])
    # long_term_memory — cross-session reusable knowledge
    await db.long_term_memory.create_index([("target_type", ASCENDING)])
    await db.long_term_memory.create_index([("tags", ASCENDING)])
    await db.long_term_memory.create_index([("created_at", DESCENDING)])
    # evidence_collection — structured evidence per session
    await db.evidence.create_index([("session_id", ASCENDING), ("phase", ASCENDING)])
    await db.evidence.create_index([("session_id", ASCENDING), ("evidence_type", ASCENDING)])
    # mitre_mappings — ATT&CK technique mappings per session
    await db.mitre_mappings.create_index([("session_id", ASCENDING)])
    # Phase 4: Subagent collections
    # credentials — discovered credentials across all phases
    await db.credentials.create_index([("session_id", ASCENDING), ("service", ASCENDING)])
    await db.credentials.create_index([("session_id", ASCENDING), ("host", ASCENDING)])
    # tunnels — network tunnels and pivots
    await db.tunnels.create_index([("session_id", ASCENDING), ("active", ASCENDING)])
    # persistence — persistence mechanisms
    await db.persistence.create_index([("session_id", ASCENDING), ("host", ASCENDING)])
    # subagent_results — full subagent execution results
    await db.subagent_results.create_index([("session_id", ASCENDING), ("agent", ASCENDING)])
    await db.subagent_results.create_index([("session_id", ASCENDING), ("subagent_name", ASCENDING)])
    # rag_history — RAG query/result pairs
    await db.rag_history.create_index([("session_id", ASCENDING), ("timestamp", DESCENDING)])
    # attack_chains — identified multi-step exploit chains
    await db.attack_chains.create_index([("session_id", ASCENDING)])
    # ── Multi-host compound indexes (session_id + host for per-IP queries) ──
    await db.findings.create_index([("session_id", ASCENDING), ("host", ASCENDING)])
    await db.tool_outputs.create_index([("session_id", ASCENDING), ("target", ASCENDING)])
    await db.credentials.create_index([("session_id", ASCENDING), ("host", ASCENDING)])
    await db.persistence.create_index([("session_id", ASCENDING), ("host", ASCENDING)])
    print("[DB] Indexes created.")


def _oid() -> str:
    """Generate a new MongoDB ObjectId as string."""
    return str(ObjectId())


def _serialize(doc: Dict) -> Dict:
    """Convert MongoDB _id to string id for JSON serialization."""
    if doc is None:
        return None
    doc = dict(doc)
    if "_id" in doc:
        doc["id"] = str(doc.pop("_id"))
    # Convert any nested ObjectId
    for k, v in doc.items():
        if isinstance(v, ObjectId):
            doc[k] = str(v)
        elif isinstance(v, datetime):
            iso = v.isoformat()
            # Naive datetimes (datetime.utcnow()) have no tzinfo — append Z so
            # JavaScript parses them as UTC rather than local time.
            if v.tzinfo is None:
                iso += 'Z'
            doc[k] = iso
    return doc


def _serialize_list(docs) -> List[Dict]:
    return [_serialize(d) for d in docs if d]


# ═══════════════════════════════════════════════════════════
#  SESSIONS
# ═══════════════════════════════════════════════════════════

async def create_session(data: SessionCreate) -> Dict:
    """Create a new pentest session. Returns the created session dict."""
    db = get_db()
    doc = {
        "_id":               ObjectId(),
        "target_ip":         data.target_ip,
        "target_hostname":   data.target_hostname,
        "target_type":       data.target_type,
        "scope":             data.scope,
        "notes":             data.notes,
        "threading_enabled": data.threading_enabled,
        "max_threads":       data.max_threads,
        "status":            SessionStatus.ACTIVE,
        "current_phase":     AttackPhase.RECON,
        "phases_completed":  [],
        "started_at":        datetime.utcnow(),
        "updated_at":        datetime.utcnow(),
        "completed_at":      None,
        "findings_count":    0,
        "tools_run":         0,
        "flags_found":       [],
        # Multi-host fields
        "session_mode":      getattr(data, "session_mode", "single"),
        "max_parallel_hosts": getattr(data, "max_parallel_hosts", 5),
        "discovered_hosts":  [],
        "hosts_completed":   [],
        "host_count":        0,
    }
    await db.sessions.insert_one(doc)
    return _serialize(doc)


async def get_session(session_id: str) -> Optional[Dict]:
    """Get a session by ID."""
    db = get_db()
    try:
        doc = await db.sessions.find_one({"_id": ObjectId(session_id)})
        return _serialize(doc) if doc else None
    except InvalidId:
        return None


async def list_sessions(limit: int = 50) -> List[Dict]:
    """List all sessions, newest first."""
    db = get_db()
    cursor = db.sessions.find().sort("started_at", DESCENDING).limit(limit)
    return _serialize_list(await cursor.to_list(length=limit))


async def delete_session(session_id: str) -> bool:
    """
    Permanently delete a session and ALL related data:
    findings, tool outputs, agent logs, flags, attack graph nodes/edges,
    shells, payloads, and OSINT results.
    Returns True if session was found and deleted.
    """
    db = get_db()
    try:
        oid = ObjectId(session_id)
    except InvalidId:
        return False

    # Verify it exists first
    session = await db.sessions.find_one({"_id": oid})
    if not session:
        return False

    # Delete all related collections in parallel
    import asyncio
    await asyncio.gather(
        db.findings.delete_many({"session_id": session_id}),
        db.tool_outputs.delete_many({"session_id": session_id}),
        db.agent_logs.delete_many({"session_id": session_id}),
        db.flags.delete_many({"session_id": session_id}),
        db.graph_nodes.delete_many({"session_id": session_id}),
        db.graph_edges.delete_many({"session_id": session_id}),
        db.shell_sessions.delete_many({"session_id": session_id}),
        db.payloads.delete_many({"session_id": session_id}),
        db.osint_results.delete_many({"session_id": session_id}),
        return_exceptions=True  # don't fail if a collection doesn't exist
    )

    # Finally delete the session document itself
    result = await db.sessions.delete_one({"_id": oid})
    return result.deleted_count > 0


async def update_session(session_id: str, updates: Dict) -> bool:
    """Update session fields."""
    db = get_db()
    updates["updated_at"] = datetime.utcnow()
    try:
        result = await db.sessions.update_one(
            {"_id": ObjectId(session_id)},
            {"$set": updates}
        )
        return result.modified_count > 0
    except InvalidId:
        return False


async def update_session_phase(session_id: str, phase: AttackPhase) -> bool:
    """Update current attack phase and mark previous as completed."""
    db = get_db()
    session = await get_session(session_id)
    if not session:
        return False
    completed = session.get("phases_completed", [])
    prev_phase = session.get("current_phase")
    if prev_phase and prev_phase not in completed:
        completed.append(prev_phase)
    try:
        result = await db.sessions.update_one(
            {"_id": ObjectId(session_id)},
            {"$set": {
                "current_phase":    phase,
                "phases_completed": completed,
                "updated_at":       datetime.utcnow()
            }}
        )
        return result.modified_count > 0
    except InvalidId:
        return False


async def increment_session_stats(session_id: str, findings: int = 0, tools: int = 0):
    """Increment findings_count and tools_run counters."""
    db = get_db()
    inc = {}
    if findings: inc["findings_count"] = findings
    if tools:    inc["tools_run"]      = tools
    if inc:
        try:
            await db.sessions.update_one(
                {"_id": ObjectId(session_id)},
                {"$inc": inc, "$set": {"updated_at": datetime.utcnow()}}
            )
        except InvalidId:
            pass


async def add_discovered_host(session_id: str, host: str) -> None:
    """Atomically add a live host to session.discovered_hosts and increment host_count."""
    db = get_db()
    try:
        await db.sessions.update_one(
            {"_id": ObjectId(session_id)},
            {
                "$addToSet": {"discovered_hosts": host},
                "$inc":      {"host_count": 1},
                "$set":      {"updated_at": datetime.utcnow()},
            }
        )
    except InvalidId:
        pass


async def mark_host_complete(session_id: str, host: str) -> None:
    """Mark a specific host as fully tested."""
    db = get_db()
    try:
        await db.sessions.update_one(
            {"_id": ObjectId(session_id)},
            {
                "$addToSet": {"hosts_completed": host},
                "$set":      {"updated_at": datetime.utcnow()},
            }
        )
    except InvalidId:
        pass


async def get_hosts_for_session(session_id: str) -> Dict:
    """Return discovered_hosts, hosts_completed, host_count and session_mode."""
    db = get_db()
    try:
        doc = await db.sessions.find_one(
            {"_id": ObjectId(session_id)},
            {"discovered_hosts": 1, "hosts_completed": 1, "host_count": 1, "session_mode": 1}
        )
    except InvalidId:
        return {}
    if not doc:
        return {}
    return {
        "discovered_hosts": doc.get("discovered_hosts", []),
        "hosts_completed":  doc.get("hosts_completed", []),
        "host_count":       doc.get("host_count", 0),
        "session_mode":     doc.get("session_mode", "single"),
    }


async def add_flag_to_session(session_id: str, flag_value: str):
    """Append flag to session's flags_found list."""
    db = get_db()
    try:
        await db.sessions.update_one(
            {"_id": ObjectId(session_id)},
            {"$addToSet": {"flags_found": flag_value},
             "$set": {"updated_at": datetime.utcnow()}}
        )
    except InvalidId:
        pass


# ═══════════════════════════════════════════════════════════
#  FINDINGS
# ═══════════════════════════════════════════════════════════

async def store_finding(
    session_id:  str,
    agent:       AgentName,
    phase:       AttackPhase,
    severity:    FindingSeverity,
    title:       str,
    description: str,
    host:        str,
    port:        Optional[int]  = None,
    service:     Optional[str]  = None,
    cves:        List[str]      = None,
    exploits:    List[str]      = None,
    tool_used:   Optional[str]  = None,
    raw_output:  Optional[str]  = None,
    extra:       Dict           = None
) -> Dict:
    """Store a new finding. Returns created document."""
    db = get_db()
    doc = {
        "_id":         ObjectId(),
        "session_id":  session_id,
        "agent":       agent,
        "phase":       phase,
        "severity":    severity,
        "title":       title,
        "description": description,
        "host":        host,
        "port":        port,
        "service":     service,
        "protocol":    None,
        "cves":        cves or [],
        "exploits":    exploits or [],
        "tool_used":   tool_used,
        "raw_output":  raw_output,
        "screenshot":  None,
        "remediation": None,
        "found_at":    datetime.utcnow(),
        "verified":    False,
        "extra":       extra or {}
    }
    await db.findings.insert_one(doc)
    # Update session counter
    await increment_session_stats(session_id, findings=1)
    return _serialize(doc)


async def get_findings(
    session_id: str,
    severity:   Optional[str] = None,
    phase:      Optional[str] = None,
    host:       Optional[str] = None,
) -> List[Dict]:
    """Get all findings for a session, optionally filtered by severity, phase, or host."""
    db = get_db()
    query = {"session_id": session_id}
    if severity: query["severity"] = severity
    if phase:    query["phase"]    = phase
    if host:     query["host"]     = host
    cursor = db.findings.find(query).sort("found_at", DESCENDING)
    return _serialize_list(await cursor.to_list(length=1000))


async def get_findings_summary(session_id: str, host: Optional[str] = None) -> Dict:
    """Return count by severity, optionally scoped to a single host."""
    db = get_db()
    match = {"session_id": session_id}
    if host:
        match["host"] = host
    pipeline = [
        {"$match": match},
        {"$group": {"_id": "$severity", "count": {"$sum": 1}}}
    ]
    results = await db.findings.aggregate(pipeline).to_list(length=10)
    summary = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0, "total": 0}
    for r in results:
        sev = r["_id"]
        cnt = r["count"]
        summary[sev] = cnt
        summary["total"] += cnt
    return summary


# ═══════════════════════════════════════════════════════════
#  TOOL OUTPUTS
# ═══════════════════════════════════════════════════════════

async def store_tool_output(
    session_id: str,
    agent:      AgentName,
    phase:      AttackPhase,
    tool_name:  str,
    command:    str,
    target:     Optional[str] = None,
    thread_id:  Optional[str] = None
) -> str:
    """
    Create a tool output record (empty). 
    Returns the record ID — use update_tool_output() as output streams in.
    """
    db = get_db()
    doc = {
        "_id":          ObjectId(),
        "session_id":   session_id,
        "agent":        agent,
        "phase":        phase,
        "tool_name":    tool_name,
        "command":      command,
        "target":       target,
        "stdout":       "",
        "stderr":       "",
        "exit_code":    None,
        "summary":      None,
        "key_findings": [],
        "started_at":   datetime.utcnow(),
        "ended_at":     None,
        "duration_ms":  None,
        "thread_id":    thread_id
    }
    await db.tool_outputs.insert_one(doc)
    await increment_session_stats(session_id, tools=1)
    return str(doc["_id"])


async def append_tool_stdout(output_id: str, chunk: str):
    """Append streaming stdout chunk to tool output record."""
    db = get_db()
    try:
        await db.tool_outputs.update_one(
            {"_id": ObjectId(output_id)},
            {"$push": {"stdout_chunks": chunk},
             "$set":  {"last_chunk_at": datetime.utcnow()}}
        )
    except InvalidId:
        pass


async def finalize_tool_output(
    output_id: str,
    stdout:    str,
    stderr:    str,
    exit_code: int,
    summary:   Optional[str]  = None,
    key_findings: List[str]   = None
):
    """Mark tool output as complete with final output."""
    db = get_db()
    now = datetime.utcnow()
    try:
        doc = await db.tool_outputs.find_one({"_id": ObjectId(output_id)})
        started = doc["started_at"] if doc else now
        duration_ms = int((now - started).total_seconds() * 1000)
        await db.tool_outputs.update_one(
            {"_id": ObjectId(output_id)},
            {"$set": {
                "stdout":       stdout,
                "stderr":       stderr,
                "exit_code":    exit_code,
                "summary":      summary,
                "key_findings": key_findings or [],
                "ended_at":     now,
                "duration_ms":  duration_ms
            }}
        )
    except (InvalidId, TypeError):
        pass


async def get_tool_outputs(session_id: str, agent: Optional[str] = None, limit: int = 100) -> List[Dict]:
    """Get tool outputs for a session."""
    db = get_db()
    query = {"session_id": session_id}
    if agent: query["agent"] = agent
    cursor = db.tool_outputs.find(query).sort("started_at", DESCENDING).limit(limit)
    return _serialize_list(await cursor.to_list(length=limit))


# ═══════════════════════════════════════════════════════════
#  AGENT LOGS
# ═══════════════════════════════════════════════════════════

async def log_agent_action(
    session_id:    str,
    agent:         AgentName,
    phase:         AttackPhase,
    action:        str,
    reasoning:     str,
    new_status:    AgentStatus,
    prev_status:   Optional[AgentStatus] = None,
    tool:          Optional[str]         = None,
    sent_to:       Optional[AgentName]   = None,
    received_from: Optional[AgentName]   = None,
    message:       Optional[str]         = None
) -> Dict:
    """Log an agent decision or status change."""
    db = get_db()
    doc = {
        "_id":           ObjectId(),
        "session_id":    session_id,
        "agent":         agent,
        "phase":         phase,
        "action":        action,
        "reasoning":     reasoning,
        "tool":          tool,
        "prev_status":   prev_status,
        "new_status":    new_status,
        "timestamp":     datetime.utcnow(),
        "sent_to":       sent_to,
        "received_from": received_from,
        "message":       message
    }
    await db.agent_logs.insert_one(doc)
    return _serialize(doc)


async def get_agent_logs(session_id: str, agent: Optional[str] = None, limit: int = 200) -> List[Dict]:
    """Get agent logs, newest first."""
    db = get_db()
    query = {"session_id": session_id}
    if agent: query["agent"] = agent
    cursor = db.agent_logs.find(query).sort("timestamp", DESCENDING).limit(limit)
    return _serialize_list(await cursor.to_list(length=limit))


# ═══════════════════════════════════════════════════════════
#  SHELL SESSIONS
# ═══════════════════════════════════════════════════════════

async def create_shell_session(
    session_id: str,
    shell_type: str,
    rhost:      str,
    lhost:      Optional[str] = None,
    lport:      Optional[int] = None,
    rport:      Optional[int] = None,
    protocol:   str = "tcp"
) -> Dict:
    """Create a new shell session record."""
    db = get_db()
    doc = {
        "_id":         ObjectId(),
        "session_id":  session_id,
        "agent":       AgentName.SHELL,
        "shell_type":  shell_type,
        "lhost":       lhost,
        "lport":       lport,
        "rhost":       rhost,
        "rport":       rport,
        "protocol":    protocol,
        "active":      False,
        "pid":         None,
        "shell_user":  None,
        "shell_cwd":   None,
        "commands":    [],
        "opened_at":   datetime.utcnow(),
        "closed_at":   None
    }
    await db.shell_sessions.insert_one(doc)
    return _serialize(doc)


async def update_shell_session(shell_id: str, updates: Dict) -> bool:
    """Update shell session fields."""
    db = get_db()
    try:
        result = await db.shell_sessions.update_one(
            {"_id": ObjectId(shell_id)},
            {"$set": updates}
        )
        return result.modified_count > 0
    except InvalidId:
        return False


async def append_shell_command(shell_id: str, cmd: str, output: str):
    """Add a command to shell session history."""
    db = get_db()
    entry = {"cmd": cmd, "output": output, "ts": datetime.utcnow().isoformat()}
    try:
        await db.shell_sessions.update_one(
            {"_id": ObjectId(shell_id)},
            {"$push": {"commands": entry}}
        )
    except InvalidId:
        pass


async def get_shell_sessions(session_id: str, active_only: bool = False) -> List[Dict]:
    """Get all shell sessions for a pentest session."""
    db = get_db()
    query = {"session_id": session_id}
    if active_only: query["active"] = True
    cursor = db.shell_sessions.find(query).sort("opened_at", DESCENDING)
    return _serialize_list(await cursor.to_list(length=50))


# ═══════════════════════════════════════════════════════════
#  FLAGS
# ═══════════════════════════════════════════════════════════

async def store_flag(
    session_id: str,
    flag_type:  str,
    value:      str,
    location:   str,
    found_by:   AgentName,
    context:    Optional[str] = None
) -> Dict:
    """Store a captured flag."""
    db = get_db()
    doc = {
        "_id":        ObjectId(),
        "session_id": session_id,
        "flag_type":  flag_type,
        "value":      value,
        "location":   location,
        "found_by":   found_by,
        "context":    context,
        "found_at":   datetime.utcnow()
    }
    await db.flags.insert_one(doc)
    await add_flag_to_session(session_id, value)
    return _serialize(doc)


async def get_flags(session_id: str) -> List[Dict]:
    """Get all flags for a session."""
    db = get_db()
    cursor = db.flags.find({"session_id": session_id}).sort("found_at", ASCENDING)
    return _serialize_list(await cursor.to_list(length=100))


# ═══════════════════════════════════════════════════════════
#  ATTACK GRAPH
# ═══════════════════════════════════════════════════════════

async def add_attack_node(
    session_id: str,
    node_id:    str,
    node_type:  str,
    label:      str,
    phase:      AttackPhase,
    host:       Optional[str] = None,
    port:       Optional[int] = None,
    severity:   Optional[FindingSeverity] = None,
    metadata:   Dict = None
) -> Dict:
    """Add a node to the attack graph."""
    db = get_db()
    # Upsert — update if exists, insert if new
    doc = {
        "node_id":    node_id,
        "session_id": session_id,
        "node_type":  node_type,
        "label":      label,
        "phase":      phase,
        "host":       host,
        "port":       port,
        "severity":   severity,
        "metadata":   metadata or {},
        "created_at": datetime.utcnow()
    }
    await db.attack_graph_nodes.update_one(
        {"node_id": node_id, "session_id": session_id},
        {"$set": doc},
        upsert=True
    )
    return doc


async def add_attack_edge(
    session_id: str,
    edge_id:    str,
    source:     str,
    target:     str,
    label:      str,
    tool:       Optional[str] = None
) -> Dict:
    """Add an edge to the attack graph."""
    db = get_db()
    doc = {
        "edge_id":    edge_id,
        "session_id": session_id,
        "source":     source,
        "target":     target,
        "label":      label,
        "tool":       tool,
        "created_at": datetime.utcnow()
    }
    await db.attack_graph_edges.update_one(
        {"edge_id": edge_id, "session_id": session_id},
        {"$set": doc},
        upsert=True
    )
    return doc


async def get_attack_graph(session_id: str) -> Dict:
    """
    Get the full attack graph, enriched with ALL findings data.
    Like Bloodhound — builds a relationship graph from:
      hosts → services → vulnerabilities → findings → credentials → access
    Merges stored graph nodes/edges with live findings from DB.
    """
    import asyncio as _asyncio

    db = get_db()

    (raw_nodes, raw_edges, findings, flags, session) = await _asyncio.gather(
        db.attack_graph_nodes.find({"session_id": session_id}).to_list(500),
        db.attack_graph_edges.find({"session_id": session_id}).to_list(500),
        db.findings.find({"session_id": session_id}).to_list(500),
        db.flags.find({"session_id": session_id}).to_list(100),
        db.sessions.find_one({"_id": __import__("bson").ObjectId(session_id)}
                              if len(session_id) == 24 else {"session_id": session_id}),
        return_exceptions=True
    )

    def _safe(v, d): return d if isinstance(v, Exception) else (v or d)
    raw_nodes = _safe(raw_nodes, [])
    raw_edges = _safe(raw_edges, [])
    findings  = _safe(findings, [])
    flags     = _safe(flags, [])
    session   = _safe(session, {})

    # Serialize stored nodes/edges
    nodes = []
    edges = []
    node_ids = set()
    edge_ids = set()

    def add_node(node_id, node_type, label, host=None, port=None,
                 severity=None, metadata=None, phase=None):
        if node_id in node_ids:
            return
        node_ids.add(node_id)
        nodes.append({
            "node_id":   node_id,
            "node_type": node_type,
            "label":     label[:40] if label else label,
            "host":      host,
            "port":      port,
            "severity":  str(severity) if severity else None,
            "phase":     phase,
            "metadata":  metadata or {}
        })

    def add_edge(source, target, label, tool=None):
        edge_id = f"{source}→{target}"
        if edge_id in edge_ids:
            return
        edge_ids.add(edge_id)
        edges.append({
            "edge_id": edge_id,
            "source":  source,
            "target":  target,
            "label":   label,
            "tool":    tool
        })

    # ── 1. Existing graph nodes (hosts + services from scanner) ───────────────
    for n in raw_nodes:
        nid = n.get("node_id", "")
        if not nid:
            continue
        node_ids.add(nid)
        d = {k: v for k, v in n.items() if k not in ("_id","session_id")}
        # Ensure node_type field (older records use "type")
        d["node_type"] = d.get("node_type") or d.get("type") or "host"
        nodes.append(d)

    for e in raw_edges:
        eid = e.get("edge_id", "")
        if not eid:
            continue
        edge_ids.add(eid)
        edges.append({k: v for k, v in e.items() if k not in ("_id","session_id")})

    # ── 2. Target host node (always present) ──────────────────────────────────
    target_ip = (session or {}).get("target_ip", "unknown") if isinstance(session, dict) else "unknown"
    target_nid = f"host_{target_ip.replace('.','_')}"
    add_node(target_nid, "host", target_ip, host=target_ip, phase="recon",
             metadata={"role": "primary_target"})

    # ── 3. Finding nodes — one node per finding, linked to host/service ────────
    sev_colors = {"critical": "critical", "high": "high", "medium": "medium", "low": "low"}
    for f in findings:
        fid    = str(f.get("_id", ""))
        title  = (f.get("title") or "Finding")[:50]
        host   = f.get("host") or target_ip
        port   = f.get("port")
        sev    = str(f.get("severity") or "low").lower()
        tool   = f.get("tool_used") or ""
        cves   = f.get("cves") or []
        phase  = f.get("phase") or "scan"

        # Service node
        svc_nid = f"svc_{host.replace('.','_')}_{port}" if port else f"host_{host.replace('.','_')}"
        if port:
            service = (f.get("service") or "unknown")
            add_node(svc_nid, "service", f"{service}:{port}", host=host, port=port, phase=phase)
            add_edge(target_nid, svc_nid, "has_service", tool="nmap")

        # Finding node
        finding_nid = f"finding_{fid}" if fid else f"finding_{title[:20].replace(' ','_')}"
        add_node(finding_nid, "vulnerability" if sev in ("critical","high") else "finding",
                 title, host=host, port=port, severity=sev, phase=phase,
                 metadata={"cves": cves, "tool": tool, "description": (f.get("description") or "")[:200]})
        add_edge(svc_nid if port else target_nid, finding_nid,
                 f"{sev} finding", tool=tool)

        # CVE nodes — link CVEs to findings
        for cve in cves[:5]:
            cve_nid = f"cve_{cve.replace('-','_')}"
            add_node(cve_nid, "vulnerability", cve, host=host, severity="high",
                     phase=phase, metadata={"cve_id": cve})
            add_edge(finding_nid, cve_nid, "references", tool="searchsploit")

        # Exploit node if tool suggests exploitation
        if any(t in tool.lower() for t in ("sqlmap","metasploit","hydra","exploit")):
            exp_nid = f"exploit_{finding_nid}"
            add_node(exp_nid, "exploit", f"via {tool}", host=host, severity=sev,
                     phase="exploit", metadata={"tool": tool})
            add_edge(finding_nid, exp_nid, "exploitable_with", tool=tool)

    # ── 4. Credential nodes ────────────────────────────────────────────────────
    # Pull credentials from agent_logs / findings metadata
    cred_findings = [f for f in findings if "credential" in (f.get("title") or "").lower()
                     or "password" in (f.get("description") or "").lower()
                     or "valid cred" in (f.get("title") or "").lower()]
    for cf in cred_findings:
        cred_nid = f"cred_{str(cf.get('_id',''))}"
        host     = cf.get("host") or target_ip
        add_node(cred_nid, "access", f"Creds: {(cf.get('title') or '')[:30]}",
                 host=host, severity="high", phase="exploit",
                 metadata={"source": cf.get("tool_used","")})
        src_nid = f"host_{host.replace('.','_')}"
        add_edge(src_nid, cred_nid, "credentials_found", tool=cf.get("tool_used",""))

    # ── 5. Shell/access nodes from flags ───────────────────────────────────────
    for fl in flags:
        ft       = fl.get("flag_type","?")
        location = fl.get("location","")
        fval     = (fl.get("value") or "")[:20]
        flag_nid = f"flag_{ft}_{str(fl.get('_id',''))}"
        add_node(flag_nid, "access",
                 f"{'Root' if ft=='root' else 'User'} flag: {fval}",
                 host=target_ip, severity="critical", phase="privesc" if ft=="root" else "exploit",
                 metadata={"flag_type": ft, "location": location})
        add_edge(target_nid, flag_nid,
                 "compromised → root" if ft=="root" else "compromised → user",
                 tool="shell")

    return {"nodes": nodes, "edges": edges}


# ═══════════════════════════════════════════════════════════
#  OSINT RESULTS
# ═══════════════════════════════════════════════════════════

async def store_osint_result(
    session_id:  str,
    query:       str,
    source:      str,
    title:       str,
    summary:     str,
    url:         Optional[str]  = None,
    cves:        List[str]      = None,
    exploits:    List[str]      = None,
    severity:    Optional[FindingSeverity] = None,
    relevance:   float          = 0.0,
    raw:         Optional[Dict] = None
) -> Dict:
    """Store an OSINT/internet research result."""
    db = get_db()
    doc = {
        "_id":             ObjectId(),
        "session_id":      session_id,
        "query":           query,
        "source":          source,
        "title":           title,
        "url":             url,
        "summary":         summary,
        "cves":            cves or [],
        "exploits":        exploits or [],
        "severity":        severity,
        "raw":             raw,
        "relevance_score": relevance,
        "fetched_at":      datetime.utcnow()
    }
    await db.osint_results.insert_one(doc)
    return _serialize(doc)


async def get_osint_results(session_id: str, min_relevance: float = 0.0) -> List[Dict]:
    """Get OSINT results sorted by relevance."""
    db = get_db()
    cursor = db.osint_results.find(
        {"session_id": session_id, "relevance_score": {"$gte": min_relevance}}
    ).sort("relevance_score", DESCENDING)
    return _serialize_list(await cursor.to_list(length=200))


# ═══════════════════════════════════════════════════════════
#  UTILITY
# ═══════════════════════════════════════════════════════════

async def get_session_summary(session_id: str) -> Dict:
    """
    Return a complete session summary for frontend hydration.
    Includes EVERYTHING needed to restore a session's state in the UI:
    session info, findings, flags, graph, tool outputs, logs, intel.
    """
    session  = await get_session(session_id)
    if not session:
        return {"error": "Session not found"}

    import asyncio as _asyncio

    # Fetch all data in parallel for speed
    (
        findings_summary,
        findings_list,
        flags,
        shells,
        recent_logs,
        graph,
        tool_outputs,
    ) = await _asyncio.gather(
        get_findings_summary(session_id),
        get_findings(session_id),
        get_flags(session_id),
        get_shell_sessions(session_id),
        get_agent_logs(session_id, limit=50),
        get_attack_graph(session_id),
        get_tool_outputs(session_id, limit=100),
        return_exceptions=True
    )

    # Safe-default any failed fetches
    def _safe(v, default):
        return default if isinstance(v, Exception) else (v or default)

    return {
        "session":        session,
        "findings":       _safe(findings_summary, {}),
        "findings_list":  _safe(findings_list, []),
        "flags":          _safe(flags, []),
        "shells":         [s for s in _safe(shells, []) if s.get("active")],
        "recent_logs":    _safe(recent_logs, []),
        "graph":          _safe(graph, {"nodes": [], "edges": []}),
        "tool_outputs":   _safe(tool_outputs, []),
        "current_phase":  session.get("current_phase", "idle"),
        "phases_completed": session.get("phases_completed", []),
    }


async def health_check() -> Dict:
    """Check MongoDB connectivity."""
    try:
        db = get_db()
        await db.command("ping")
        return {"status": "ok", "db": DB_NAME}
    except Exception as e:
        return {"status": "error", "error": str(e)}


# ═══════════════════════════════════════════════════════════
#  PAYLOADS  (Phase 3 — msfvenom generated files)
# ═══════════════════════════════════════════════════════════

async def store_payload(
    session_id:    str,
    platform:      str,
    arch:          str,
    fmt:           str,
    lhost:         str,
    lport:         int,
    payload_name:  str,
    output_path:   str,
    msfvenom_cmd:  str,
    listener_cmd:  str,
    success:       bool,
    encoder:       Optional[str] = None,
    iterations:    int = 1,
    size_bytes:    Optional[int] = None,
    error:         Optional[str] = None,
    raw_output:    Optional[str] = None
) -> Dict:
    """Store a msfvenom payload generation record."""
    db = get_db()
    doc = {
        "_id":          ObjectId(),
        "session_id":   session_id,
        "platform":     platform,
        "arch":         arch,
        "format":       fmt,
        "lhost":        lhost,
        "lport":        lport,
        "encoder":      encoder,
        "iterations":   iterations,
        "payload_name": payload_name,
        "output_path":  output_path,
        "size_bytes":   size_bytes,
        "msfvenom_cmd": msfvenom_cmd,
        "listener_cmd": listener_cmd,
        "success":      success,
        "error":        error,
        "raw_output":   raw_output,
        "generated_at": datetime.utcnow()
    }
    await db.payloads.insert_one(doc)
    return _serialize(doc)


async def get_payloads(session_id: str) -> List[Dict]:
    """Get all payloads for a session, newest first."""
    db = get_db()
    cursor = db.payloads.find({"session_id": session_id}).sort("generated_at", DESCENDING)
    return _serialize_list(await cursor.to_list(length=100))


async def get_payload(payload_id: str) -> Optional[Dict]:
    """Get a single payload by ID."""
    db = get_db()
    try:
        doc = await db.payloads.find_one({"_id": ObjectId(payload_id)})
        return _serialize(doc) if doc else None
    except InvalidId:
        return None


async def delete_payload(payload_id: str) -> bool:
    """Delete a payload record from the database."""
    db = get_db()
    try:
        result = await db.payloads.delete_one({"_id": ObjectId(payload_id)})
        return result.deleted_count > 0
    except InvalidId:
        return False




# ═══════════════════════════════════════════════════════════
#  ATTACK TREE  (Attack Planner output)
# ═══════════════════════════════════════════════════════════

async def store_attack_tree(session_id: str, tree: Dict) -> Dict:
    """
    Store the attack plan/tree generated by the Attack Planner.
    tree = {
      "root": "Initial Access",
      "nodes": [{"id": "n1", "technique": "...", "tool": "...", "probability": 0.8}],
      "edges": [{"from": "n1", "to": "n2", "condition": "success"}],
      "optimal_path": ["n1", "n3", "n5"],
      "mitre_techniques": ["T1190", "T1059"],
      "reasoning": "..."
    }
    """
    db = get_db()
    doc = {
        "_id":        ObjectId(),
        "session_id": session_id,
        "tree":       tree,
        "created_at": datetime.utcnow()
    }
    await db.attack_tree.insert_one(doc)
    return _serialize(doc)


async def get_attack_tree(session_id: str) -> Optional[Dict]:
    """Get the most recent attack tree for a session."""
    db = get_db()
    doc = await db.attack_tree.find_one(
        {"session_id": session_id},
        sort=[("created_at", DESCENDING)]
    )
    return _serialize(doc) if doc else None


# ═══════════════════════════════════════════════════════════
#  CHAIN ANALYSES  (produced by AttackGraphAgent)
# ═══════════════════════════════════════════════════════════

async def get_chain_analyses(session_id: str, limit: int = 10) -> List[Dict]:
    """Return the most recent chain analyses for a session."""
    db = get_db()
    cursor = db.chain_analyses.find(
        {"session_id": session_id}
    ).sort("created_at", DESCENDING).limit(limit)
    return _serialize_list(await cursor.to_list(length=limit))


async def get_latest_chain_analysis(session_id: str) -> Optional[Dict]:
    """Return only the single most recent chain analysis."""
    results = await get_chain_analyses(session_id, limit=1)
    return results[0] if results else None


# ═══════════════════════════════════════════════════════════
#  LONG-TERM MEMORY  (cross-session reusable knowledge)
# ═══════════════════════════════════════════════════════════

async def store_memory(
    memory_type:  str,    # "exploit_pattern" | "tool_reliability" | "credential_pattern"
    target_type:  str,    # "linux" | "windows" | "web" | "ad"
    content:      Dict,   # the knowledge payload
    tags:         List[str] = None,
    success:      bool = True,
    confidence:   float = 0.8
) -> Dict:
    """
    Store a reusable knowledge entry in long-term memory.
    Called after any successful or notable exploitation event.
    """
    db = get_db()
    doc = {
        "_id":         ObjectId(),
        "memory_type": memory_type,
        "target_type": target_type,
        "content":     content,
        "tags":        tags or [],
        "success":     success,
        "confidence":  confidence,
        "use_count":   0,
        "created_at":  datetime.utcnow(),
        "last_used":   None
    }
    await db.long_term_memory.insert_one(doc)
    return _serialize(doc)


async def recall_memory(
    memory_type:  Optional[str] = None,
    target_type:  Optional[str] = None,
    tags:         Optional[List[str]] = None,
    min_confidence: float = 0.5,
    limit:        int = 10
) -> List[Dict]:
    """
    Retrieve relevant memories filtered by type, target, tags.
    Returns most confident entries first.
    """
    db = get_db()
    query: Dict = {"confidence": {"$gte": min_confidence}}
    if memory_type:  query["memory_type"] = memory_type
    if target_type:  query["target_type"] = target_type
    if tags:         query["tags"] = {"$in": tags}

    cursor = db.long_term_memory.find(query)                 .sort([("confidence", DESCENDING), ("use_count", DESCENDING)])                 .limit(limit)
    docs = await cursor.to_list(length=limit)
    # Increment use_count for retrieved memories
    ids = [d["_id"] for d in docs]
    if ids:
        await db.long_term_memory.update_many(
            {"_id": {"$in": ids}},
            {"$inc": {"use_count": 1}, "$set": {"last_used": datetime.utcnow()}}
        )
    return _serialize_list(docs)


async def update_memory_confidence(memory_id: str, delta: float) -> bool:
    """Increase or decrease confidence of a memory entry based on outcome."""
    db = get_db()
    try:
        # Clamp confidence to [0.0, 1.0]
        result = await db.long_term_memory.update_one(
            {"_id": ObjectId(memory_id)},
            [{"$set": {"confidence": {
                "$min": [1.0, {"$max": [0.0, {"$add": ["$confidence", delta]}]}]
            }}}]
        )
        return result.modified_count > 0
    except InvalidId:
        return False


# ═══════════════════════════════════════════════════════════
#  EVIDENCE COLLECTION
# ═══════════════════════════════════════════════════════════

async def store_evidence(
    session_id:    str,
    phase:         str,
    evidence_type: str,   # "shell_output" | "screenshot_desc" | "credential" | "file_content" | "command_transcript"
    title:         str,
    content:       str,
    host:          Optional[str] = None,
    tool_used:     Optional[str] = None,
    severity:      str = "info",
    mitre_technique: Optional[str] = None
) -> Dict:
    """Store structured evidence for reporting and proof-of-exploitation."""
    db = get_db()
    doc = {
        "_id":             ObjectId(),
        "session_id":      session_id,
        "phase":           phase,
        "evidence_type":   evidence_type,
        "title":           title,
        "content":         content[:10000],  # cap at 10KB
        "host":            host,
        "tool_used":       tool_used,
        "severity":        severity,
        "mitre_technique": mitre_technique,
        "captured_at":     datetime.utcnow()
    }
    await db.evidence.insert_one(doc)
    return _serialize(doc)


async def get_evidence(session_id: str, evidence_type: Optional[str] = None) -> List[Dict]:
    """Get all evidence for a session, optionally filtered by type."""
    db = get_db()
    query: Dict = {"session_id": session_id}
    if evidence_type:
        query["evidence_type"] = evidence_type
    cursor = db.evidence.find(query).sort("captured_at", ASCENDING)
    return _serialize_list(await cursor.to_list(length=500))


# ═══════════════════════════════════════════════════════════
#  MITRE ATT&CK MAPPING
# ═══════════════════════════════════════════════════════════

async def store_mitre_mapping(
    session_id:  str,
    technique_id: str,    # e.g. "T1190"
    technique_name: str,  # e.g. "Exploit Public-Facing Application"
    tactic:       str,    # e.g. "Initial Access"
    tool_used:    Optional[str] = None,
    host:         Optional[str] = None,
    success:      bool = False,
    evidence_ref: Optional[str] = None
) -> Dict:
    """Store a MITRE ATT&CK technique mapping for this session."""
    db = get_db()
    # Upsert — avoid duplicate technique entries per session
    doc = {
        "session_id":     session_id,
        "technique_id":   technique_id,
        "technique_name": technique_name,
        "tactic":         tactic,
        "tool_used":      tool_used,
        "host":           host,
        "success":        success,
        "evidence_ref":   evidence_ref,
        "mapped_at":      datetime.utcnow()
    }
    await db.mitre_mappings.update_one(
        {"session_id": session_id, "technique_id": technique_id},
        {"$setOnInsert": {"_id": ObjectId()}, "$set": doc},
        upsert=True
    )
    result = await db.mitre_mappings.find_one(
        {"session_id": session_id, "technique_id": technique_id}
    )
    return _serialize(result) if result else doc


async def get_mitre_mappings(session_id: str) -> List[Dict]:
    """Get all MITRE ATT&CK mappings for a session."""
    db = get_db()
    cursor = db.mitre_mappings.find({"session_id": session_id}).sort("tactic", ASCENDING)
    return _serialize_list(await cursor.to_list(length=200))


# ═══════════════════════════════════════════════════════════
#  SESSION ACTIVATION  (Phase 3 — multi-session switching)
# ═══════════════════════════════════════════════════════════

async def activate_session(session_id: str) -> Optional[Dict]:
    """
    Mark a session as ACTIVE and return its full summary.
    Used when the user switches active sessions in the frontend.
    """
    # Verify session exists
    session = await get_session(session_id)
    if not session:
        return None

    # Ensure it is marked active (resume paused/completed sessions)
    await update_session(session_id, {"status": SessionStatus.ACTIVE})

    # Return a full summary for the frontend to hydrate its store
    return await get_session_summary(session_id)
