# -*- coding: utf-8 -*-
"""Structured data model of the ARGUS engagement — the single source of truth.
Numbers reproduce the source report exactly: 40 findings (0C / 1H / 13M / 11L / 15I)."""

ENGAGEMENT = {
    "platform": "ARGUS",
    "platform_tagline": "Autonomous Offensive Security",
    "doc_type": "Autonomous Penetration Test · Engagement Report",
    "engagement_name": "Internal Network Segment — Authorized Assessment",
    "scope_cidr": "192.168.40.0/24",
    "targets": ["192.168.40.2", "192.168.40.3", "192.168.40.4", "192.168.40.8",
                "192.168.40.17", "192.168.40.21", "192.168.40.36"],
    "hosts_with_findings": 6,
    "engagement_type": "Penetration Test",
    "started": "2026-07-07 14:47 UTC",
    "completed": "In progress",
    "duration": "2h 29m 49s",
    "generated": "2026-07-07 17:17 UTC",
    "overall_risk": "HIGH",
    "overall_risk_note": "Significant issues identified",
    "access_achieved": "None",
    "findings_gate": "ARGUS Issue-Validator (evidence-grounded, severity-scaled)",
    "classification": "CONFIDENTIAL",
    "frameworks": ["MITRE ATT&CK Enterprise", "OWASP Top 10", "CVSS v3.1", "PTES"],
}

# order matters for the severity ramp (ordinal, hot -> cool)
SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Info"]
SEVERITY_COUNTS = {"Critical": 0, "High": 1, "Medium": 13, "Low": 11, "Info": 15}
TOTAL_FINDINGS = 40

# per-host severity breakdown (most severe first), exactly as reported
HOSTS = [
    {"ip": "192.168.40.8",  "label": "Crestron web host",
     "os": "Unknown", "counts": {"Critical":0,"High":1,"Medium":6,"Low":3,"Info":4}, "total":14,
     "note": "Crestron Webserver on :80 (redirects to HTTPS). Highest-risk host — carries the sole High finding plus command-injection and XSS signals."},
    {"ip": "192.168.40.4",  "label": "Multi-service / AD host",
     "os": "Windows (AD/SMB)", "counts": {"Critical":0,"High":0,"Medium":5,"Low":5,"Info":3}, "total":13,
     "note": "Broadest attack surface: legacy cleartext protocols (Telnet/REXEC/RSH), exposed RDP, five HTTP(S) ports, Active Directory/SMB and database services detected."},
    {"ip": "192.168.40.17", "label": "Web application",
     "os": "Unknown", "counts": {"Critical":0,"High":0,"Medium":1,"Low":1,"Info":1}, "total":3,
     "note": "IDOR / broken object-level authorization observed; missing security headers. Intermittent availability during testing."},
    {"ip": "192.168.40.3",  "label": "Web application",
     "os": "Unknown", "counts": {"Critical":0,"High":0,"Medium":1,"Low":1,"Info":1}, "total":3,
     "note": "IDOR / broken object-level authorization observed; missing security headers. Intermittent availability during testing."},
    {"ip": "192.168.40.21", "label": "Hikvision IoT / camera",
     "os": "Linux", "counts": {"Critical":0,"High":0,"Medium":0,"Low":1,"Info":5}, "total":6,
     "note": "Embedded Linux appliance. RTSP (Hikvision), HTTP/HTTPS and a proprietary service on :8102 exposed; missing transport security headers."},
    {"ip": "192.168.40.2",  "label": "Recon origin",
     "os": "Unknown", "counts": {"Critical":0,"High":0,"Medium":0,"Low":0,"Info":1}, "total":1,
     "note": "Engagement objective host — no foothold, credentials, or access obtained. Retained as coverage evidence."},
]

# 192.168.40.36 was in the target list but returned no observable services / no findings.
HOST_NO_DATA = "192.168.40.36"

# ---- Findings register (F-01 .. F-40) -------------------------------------
# category drives grouping, iconography and the remediation roadmap workstream.
F = [
 {"id":"F-01","sev":"High","cvss":"7.5","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing X-Content-Type-Options header (MIME sniffing)",
  "raw":"[007352] /: The X-Content-Type-Options header is not set.",
  "desc":"The X-Content-Type-Options response header is not set on the web root. A user agent may render content using a MIME type different from the one declared by the server, which can be leveraged to trigger content-sniffing based attacks.",
  "basis":"Severity HIGH as assessed by the finding producer from its collected evidence (no demonstrated compromise or validated CVE on file).",
  "evidence":"Reference: https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/missing-content-type-header/",
  "fix":"Return `X-Content-Type-Options: nosniff` on all responses. Deploy at the reverse proxy / web server so coverage is global rather than per-route."},
 {"id":"F-02","sev":"Medium","cvss":"","host":"192.168.40.17","port":"","proto":"vuln",
  "cat":"idor","mitre":"T1212",
  "title":"IDOR / BOLA — unauthorized object access (id=0)",
  "raw":"IDOR / BOLA: Unauthorized Object Access — id=0",
  "desc":"An object referenced by id=0 was accessible without an authorization check, indicating broken object-level authorization (BOLA). An attacker may enumerate identifiers to read or modify records belonging to other users.",
  "basis":"Injection signature observed but command execution was NOT demonstrated — capped pending proof of exploitation.",
  "evidence":"[CIRCUIT-BREAKER] bash against -c is in circuit-break for 599s more (after 49 unproductive calls)",
  "fix":"Enforce per-request object-level authorization: verify the authenticated principal owns or may access each referenced id. Prefer unguessable identifiers and deny-by-default access checks."},
 {"id":"F-03","sev":"Medium","cvss":"","host":"192.168.40.3","port":"","proto":"vuln",
  "cat":"idor","mitre":"T1212",
  "title":"IDOR / BOLA — unauthorized object access (id=0)",
  "raw":"IDOR / BOLA: Unauthorized Object Access — id=0",
  "desc":"An object referenced by id=0 was accessible without an authorization check, indicating broken object-level authorization (BOLA). An attacker may enumerate identifiers to read or modify records belonging to other users.",
  "basis":"Injection signature observed but command execution was NOT demonstrated — capped pending proof of exploitation.",
  "evidence":"[CIRCUIT-BREAKER] bash against -c is in circuit-break for 599s more (after 49 unproductive calls)",
  "fix":"Enforce per-request object-level authorization: verify the authenticated principal owns or may access each referenced id. Prefer unguessable identifiers and deny-by-default access checks."},
 {"id":"F-04","sev":"Medium","cvss":"","host":"192.168.40.4","port":"23","proto":"recon",
  "cat":"cleartext","mitre":"T1040",
  "title":"Cleartext protocol exposed — TELNET (port 23)",
  "raw":"Cleartext Protocol on port 23: TELNET",
  "desc":"TELNET transmits credentials and session data in plaintext. Anyone able to observe the network path can capture usernames, passwords and command output.",
  "basis":"Confirmed weakness with no applicable public exploit, but a high chance of chaining with other issues.",
  "evidence":"PORT   STATE    SERVICE VERSION\n23/tcp filtered telnet\nNmap done: 1 IP address (1 host up) scanned in 1.34 seconds",
  "fix":"Disable TELNET. Replace with SSH for administrative access and block port 23 at the host firewall and network boundary."},
 {"id":"F-05","sev":"Medium","cvss":"","host":"192.168.40.4","port":"512","proto":"recon",
  "cat":"cleartext","mitre":"T1040",
  "title":"Cleartext protocol exposed — REXEC (port 512)",
  "raw":"Cleartext Protocol on port 512: REXEC",
  "desc":"The rexec service transmits credentials and session data in plaintext and provides weak host-based trust. Credentials are recoverable by a network observer.",
  "basis":"Confirmed weakness with no applicable public exploit, but a high chance of chaining with other issues.",
  "evidence":"PORT    STATE    SERVICE VERSION\n512/tcp filtered exec\nNmap done: 1 IP address (1 host up) scanned in 1.41 seconds",
  "fix":"Disable the r-services (rexec/rlogin/rsh). Use SSH and block ports 512–514 at host and network boundaries."},
 {"id":"F-06","sev":"Medium","cvss":"","host":"192.168.40.4","port":"513","proto":"recon",
  "cat":"cleartext","mitre":"T1040",
  "title":"Cleartext protocol exposed — RSH (port 513)",
  "raw":"Cleartext Protocol on port 513: RSH",
  "desc":"The rlogin/rsh service on port 513 transmits credentials and session data in plaintext and relies on trivially spoofable host-based trust.",
  "basis":"Confirmed weakness with no applicable public exploit, but a high chance of chaining with other issues.",
  "evidence":"PORT    STATE    SERVICE VERSION\n513/tcp filtered login\nNmap done: 1 IP address (1 host up) scanned in 1.47 seconds",
  "fix":"Disable the r-services. Use SSH and block ports 512–514 at host and network boundaries."},
 {"id":"F-07","sev":"Medium","cvss":"","host":"192.168.40.4","port":"514","proto":"recon",
  "cat":"cleartext","mitre":"T1040",
  "title":"Cleartext protocol exposed — RSH (port 514)",
  "raw":"Cleartext Protocol on port 514: RSH",
  "desc":"The rsh service on port 514 transmits credentials and session data in plaintext and relies on trivially spoofable host-based trust.",
  "basis":"Confirmed weakness with no applicable public exploit, but a high chance of chaining with other issues.",
  "evidence":"PORT    STATE    SERVICE VERSION\n514/tcp filtered shell\nNmap done: 1 IP address (1 host up) scanned in 1.38 seconds",
  "fix":"Disable the r-services. Use SSH and block ports 512–514 at host and network boundaries."},
 {"id":"F-08","sev":"Medium","cvss":"","host":"192.168.40.4","port":"3389","proto":"recon",
  "cat":"rdp","mitre":"T1021.001",
  "title":"RDP without NLA / weak encryption (port 3389)",
  "raw":"RDP 3389 — No NLA / Weak Encryption",
  "desc":"Remote Desktop on 3389 lacks Network Level Authentication or negotiates weak encryption. Pre-authentication traffic may be capturable and credential brute-forcing is materially easier.",
  "basis":"Severity MEDIUM as assessed by the finding producer from its collected evidence (no demonstrated compromise or validated CVE on file).",
  "evidence":"PORT     STATE    SERVICE\n3389/tcp filtered ms-wbt-server\nNmap done: 1 IP address (1 host up) scanned in 1.23 seconds [EXIT 0]",
  "fix":"Require Network Level Authentication (NLA), enforce TLS with strong ciphers, restrict RDP to a jump host / VPN, and apply account-lockout and MFA."},
 {"id":"F-09","sev":"Medium","cvss":"","host":"192.168.40.8","port":"80","proto":"vuln",
  "cat":"cmdinjection","mitre":"T1059",
  "title":"OS command injection — likely RCE",
  "raw":"Command Injection: Likely RCE @ http://192.168.40.8",
  "desc":"An OS command-injection signature was detected at the web root, indicating an attacker may be able to execute arbitrary operating-system commands on the host. Successful exploitation would typically yield full server compromise.",
  "basis":"Injection signature observed but command execution was NOT demonstrated — capped pending proof of exploitation.",
  "evidence":"Starting commix (commix) | pid pending\ncommix started, pid: 71864\nAutomated All-in-One OS Command Injection Exploitation Tool\n(!) Legal disclaimer: usage without prior mutual consent is illegal.",
  "fix":"Treat as priority. Eliminate shell invocation on user input; use parameterized APIs and strict allow-list validation. Add a WAF virtual patch as an interim control and review server logs for exploitation attempts."},
 {"id":"F-10","sev":"Medium","cvss":"","host":"192.168.40.8","port":"","proto":"vuln",
  "cat":"idor","mitre":"T1212",
  "title":"IDOR / BOLA — unauthorized object access (id=0)",
  "raw":"IDOR / BOLA: Unauthorized Object Access — id=0",
  "desc":"An object referenced by id=0 was accessible without an authorization check, indicating broken object-level authorization on this host as well.",
  "basis":"Injection signature observed but command execution was NOT demonstrated — capped pending proof of exploitation.",
  "evidence":"[CIRCUIT-BREAKER] bash against -c is in circuit-break for 599s more (after 43 unproductive calls)",
  "fix":"Enforce per-request object-level authorization and deny-by-default access checks; prefer unguessable identifiers."},
 {"id":"F-11","sev":"Medium","cvss":"","host":"192.168.40.8","port":"80","proto":"vuln",
  "cat":"xss","mitre":"T1059.007",
  "title":"Potential XSS — flagged for manual verification",
  "raw":"XSS (nmap http-xssed): http://192.168.40.8",
  "desc":"The nmap http-xssed script queried the public xssed.com archive for this host and found no previously reported XSS, and flagged the web root for manual XSS verification. This is an unconfirmed signal — no reflected or stored sink has been demonstrated. If a sink is confirmed, XSS can hijack sessions, act as the victim, or deliver malware.",
  "basis":"Severity MEDIUM as assessed by the finding producer from its collected evidence (no demonstrated compromise or validated CVE on file). The archive lookup returned no match; manual verification is required to confirm or dismiss.",
  "evidence":"PORT   STATE SERVICE\n80/tcp open  http\n|_http-xssed: No previously reported XSS vuln.\nNmap done: 1 IP address (1 host up) scanned in 1.41 seconds [EXIT 0]",
  "fix":"Manually verify whether a reflected or stored sink exists before treating this as confirmed. If present, apply context-aware output encoding, input validation and a restrictive Content-Security-Policy."},
 {"id":"F-12","sev":"Medium","cvss":"5.0","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing security header — Content-Security-Policy",
  "raw":"[013587] /: Suggested security header missing: content-security-policy.",
  "desc":"No Content-Security-Policy header is present. CSP is a primary defense-in-depth control against XSS and data-injection; its absence increases the blast radius of client-side injection flaws.",
  "basis":"Severity MEDIUM as assessed by the finding producer from its collected evidence (no demonstrated compromise or validated CVE on file).",
  "evidence":"Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP",
  "fix":"Define and deploy a strict Content-Security-Policy (nonce/hash-based script-src, no unsafe-inline). Roll out in report-only mode first, then enforce."},
 {"id":"F-13","sev":"Medium","cvss":"5.0","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing security header — Permissions-Policy",
  "raw":"[013587] /: Suggested security header missing: permissions-policy.",
  "desc":"No Permissions-Policy header is present, so powerful browser features (camera, microphone, geolocation, etc.) are not explicitly constrained for the application origin.",
  "basis":"Severity MEDIUM as assessed by the finding producer from its collected evidence (no demonstrated compromise or validated CVE on file).",
  "evidence":"Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy",
  "fix":"Set a Permissions-Policy that disables unused features (e.g. `geolocation=(), camera=(), microphone=()`)."},
 {"id":"F-14","sev":"Medium","cvss":"5.0","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing security header — Referrer-Policy",
  "raw":"[013587] /: Suggested security header missing: referrer-policy.",
  "desc":"No Referrer-Policy header is present, which may leak full request URLs (and any embedded tokens or identifiers) to third-party destinations via the Referer header.",
  "basis":"Severity MEDIUM as assessed by the finding producer from its collected evidence (no demonstrated compromise or validated CVE on file).",
  "evidence":"Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy",
  "fix":"Set `Referrer-Policy: strict-origin-when-cross-origin` (or stricter) globally."},
 {"id":"F-15","sev":"Low","cvss":"","host":"192.168.40.17","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing security headers (4)",
  "raw":"Missing Security Headers (4)",
  "desc":"Four recommended response headers are absent: X-Frame-Options, X-Content-Type-Options, Content-Security-Policy and X-XSS-Protection.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Missing: X-Frame-Options, X-Content-Type-Options, Content-Security-Policy, X-XSS-Protection",
  "fix":"Add the modern baseline (Content-Security-Policy, HSTS, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy) at the web tier and validate in CI. Note: X-XSS-Protection is deprecated — set it to 0 or omit it and rely on CSP rather than re-enabling the legacy auditor."},
 {"id":"F-16","sev":"Low","cvss":"","host":"192.168.40.21","port":"80","proto":"recon",
  "cat":"header","mitre":"",
  "title":"Missing security headers — HTTP :80",
  "raw":"HTTP 80 — Missing Security Headers",
  "desc":"HTTP on port 80 is missing Strict-Transport-Security and Content-Security-Policy.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"HTTP/1.1 200 OK\nX-Content-Type-Options: nosniff\nX-Frame-Options: SAMEORIGIN\nX-XSS-Protection: 1; mode=block\nContent-Length: 2613",
  "fix":"Add HSTS (once HTTPS is enforced) and a Content-Security-Policy; redirect HTTP to HTTPS."},
 {"id":"F-17","sev":"Low","cvss":"","host":"192.168.40.3","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing security headers (4)",
  "raw":"Missing Security Headers (4)",
  "desc":"Four recommended response headers are absent: X-Frame-Options, X-Content-Type-Options, Content-Security-Policy and X-XSS-Protection.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Missing: X-Frame-Options, X-Content-Type-Options, Content-Security-Policy, X-XSS-Protection",
  "fix":"Add the modern baseline (Content-Security-Policy, HSTS, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy) at the web tier and validate in CI. Note: X-XSS-Protection is deprecated — set it to 0 or omit it and rely on CSP rather than re-enabling the legacy auditor."},
 {"id":"F-18","sev":"Low","cvss":"","host":"192.168.40.4","port":"443","proto":"recon",
  "cat":"header","mitre":"",
  "title":"Missing security headers — HTTPS :443",
  "raw":"HTTP 443 — Missing Security Headers",
  "desc":"HTTPS on port 443 is missing Strict-Transport-Security, X-Frame-Options, X-Content-Type-Options and Content-Security-Policy.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Starting curl (curl) | pid pending\ncurl started, pid: 74691\n[EXIT 28]",
  "fix":"Add the baseline header set including HSTS with a long max-age and preload once validated."},
 {"id":"F-19","sev":"Low","cvss":"","host":"192.168.40.4","port":"80","proto":"recon",
  "cat":"header","mitre":"",
  "title":"Missing security headers — HTTP :80",
  "raw":"HTTP 80 — Missing Security Headers",
  "desc":"HTTP on port 80 is missing Strict-Transport-Security, X-Frame-Options, X-Content-Type-Options and Content-Security-Policy.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Starting curl (curl) | pid pending\ncurl started, pid: 74640\n[EXIT 28]",
  "fix":"Redirect HTTP to HTTPS and add the baseline header set at the web tier."},
 {"id":"F-20","sev":"Low","cvss":"","host":"192.168.40.4","port":"8080","proto":"recon",
  "cat":"header","mitre":"",
  "title":"Missing security headers — HTTP :8080",
  "raw":"HTTP 8080 — Missing Security Headers",
  "desc":"HTTP on port 8080 is missing Strict-Transport-Security, X-Frame-Options, X-Content-Type-Options and Content-Security-Policy.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Starting curl (curl) | pid pending\ncurl started, pid: 74853\n[EXIT 28]",
  "fix":"Add the baseline header set; confirm whether this management/alt-HTTP port should be internet- or LAN-reachable at all."},
 {"id":"F-21","sev":"Low","cvss":"","host":"192.168.40.4","port":"8443","proto":"recon",
  "cat":"header","mitre":"",
  "title":"Missing security headers — HTTPS :8443",
  "raw":"HTTP 8443 — Missing Security Headers",
  "desc":"HTTPS on port 8443 is missing Strict-Transport-Security, X-Frame-Options, X-Content-Type-Options and Content-Security-Policy.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Starting curl (curl) | pid pending\ncurl started, pid: 74856\n[EXIT 28]",
  "fix":"Add the baseline header set including HSTS; restrict management interfaces to trusted networks."},
 {"id":"F-22","sev":"Low","cvss":"","host":"192.168.40.4","port":"8888","proto":"recon",
  "cat":"header","mitre":"",
  "title":"Missing security headers — HTTP :8888",
  "raw":"HTTP 8888 — Missing Security Headers",
  "desc":"HTTP on port 8888 is missing Strict-Transport-Security, X-Frame-Options, X-Content-Type-Options and Content-Security-Policy.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Starting curl (curl) | pid pending\ncurl started, pid: 74863\n[EXIT 28]",
  "fix":"Add the baseline header set; confirm this alt-HTTP port is intended to be exposed."},
 {"id":"F-23","sev":"Low","cvss":"","host":"192.168.40.8","port":"80","proto":"recon",
  "cat":"header","mitre":"",
  "title":"Missing security headers — HTTP :80",
  "raw":"HTTP 80 — Missing Security Headers",
  "desc":"HTTP on port 80 is missing Strict-Transport-Security and Content-Security-Policy. The server issues a 301 redirect to HTTPS and sets a Secure/HttpOnly tracking cookie.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"HTTP/1.1 301 Moved Permanently\nSet-Cookie: TRACKID=…; Path=/; Secure; HttpOnly\nLocation: https://192.168.40.8/index_banner.html\nX-Frame-Options: SAMEORIGIN",
  "fix":"Add HSTS and CSP; ensure the redirect target also carries the full header baseline."},
 {"id":"F-24","sev":"Low","cvss":"","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing security header (1) — Content-Security-Policy",
  "raw":"Missing Security Headers (1)",
  "desc":"Content-Security-Policy is missing on this endpoint.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Missing: Content-Security-Policy",
  "fix":"Deploy a Content-Security-Policy (see F-12)."},
 {"id":"F-25","sev":"Low","cvss":"","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"header","mitre":"",
  "title":"Missing security header — Strict-Transport-Security",
  "raw":"[013587] /: Suggested security header missing: strict-transport-security.",
  "desc":"No HTTP Strict-Transport-Security header is present, so browsers are not instructed to force HTTPS, leaving room for downgrade / SSL-strip attacks.",
  "basis":"Information/hygiene exposure — not directly exploitable.",
  "evidence":"Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security",
  "fix":"Set `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload` once HTTPS is enforced site-wide."},
 {"id":"F-26","sev":"Info","cvss":"","host":"192.168.40.17","port":"80","proto":"http",
  "cat":"connectfail","mitre":"",
  "title":"Endpoint unreachable during probe",
  "raw":"[FAIL] Unable to connect to 192.168.40.17:80.",
  "desc":"A probe to 192.168.40.17:80 failed to connect, indicating intermittent availability, filtering, or rate-limiting during the test window. Recorded as coverage evidence.",
  "basis":"Severity INFO as assessed by the finding producer from its collected evidence.",
  "evidence":"[FAIL] Unable to connect to 192.168.40.17:80.",
  "fix":"Confirm service availability and whether connectivity was blocked by a control; re-test to close coverage gaps."},
 {"id":"F-27","sev":"Info","cvss":"","host":"192.168.40.2","port":"","proto":"exploit",
  "cat":"noaccess","mitre":"",
  "title":"Engagement objective — no access obtained",
  "raw":"Engagement objectives — no access",
  "desc":"Outcome for this objective host: NO_ACCESS. No foothold, user flag, root flag or credentials were obtained; five informational loot items were catalogued.",
  "basis":"Severity INFO as assessed by the finding producer from its collected evidence.",
  "evidence":"Outcome: NO_ACCESS | type: pentest  foothold=N  user_flag=—  root_flag=—  creds=0  loot=5",
  "fix":"No remediation required. Positive coverage result — retain for trend comparison in future engagements."},
 {"id":"F-28","sev":"Info","cvss":"","host":"192.168.40.21","port":"","proto":"recon",
  "cat":"osfingerprint","mitre":"",
  "title":"OS fingerprint — Linux",
  "raw":"OS Fingerprint: Linux",
  "desc":"nmap OS detection identified 192.168.40.21 as Linux. Platform knowledge narrows an attacker's tool and exploit selection.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"nmap OS detection: Linux",
  "fix":"Informational. Ensure the appliance is inventoried and receives vendor firmware updates."},
 {"id":"F-29","sev":"Info","cvss":"","host":"192.168.40.21","port":"443","proto":"recon",
  "cat":"openport","mitre":"",
  "title":"Open port 443/tcp — ssl/https",
  "raw":"Open Port 443/tcp: ssl/https?",
  "desc":"Port 443/tcp is open on 192.168.40.21 (service: ssl/https). Part of the appliance's exposed surface.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"443/tcp open  ssl/https?",
  "fix":"Confirm the service is required and restrict to management networks; keep TLS configuration current."},
 {"id":"F-30","sev":"Info","cvss":"","host":"192.168.40.21","port":"554","proto":"recon",
  "cat":"openport","mitre":"",
  "title":"Open port 554/tcp — RTSP (Hikvision)",
  "raw":"Open Port 554/tcp: rtsp",
  "desc":"Port 554/tcp (RTSP) is open and the banner advertises a Hikvision device with Digest authentication. Exposed camera/RTSP services are frequent targets for default-credential and known-CVE attacks.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"554/tcp open  rtsp\nWWW-Authenticate: Digest realm=\"Hikvision\", nonce=\"3d7f4c2fc76cdb4a98558ba526041518\"",
  "fix":"Restrict RTSP to trusted networks/VLAN, change default credentials, and patch the device to current firmware."},
 {"id":"F-31","sev":"Info","cvss":"","host":"192.168.40.21","port":"80","proto":"recon",
  "cat":"openport","mitre":"",
  "title":"Open port 80/tcp — HTTP",
  "raw":"Open Port 80/tcp: http",
  "desc":"Port 80/tcp (HTTP) is open on 192.168.40.21. The management web interface of the embedded device.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"80/tcp open  http\nX-Content-Type-Options: nosniff | X-Frame-Options: SAMEORIGIN | X-XSS-Protection: 1; mode=block",
  "fix":"Redirect to HTTPS, restrict the management interface to trusted networks, and change default credentials."},
 {"id":"F-32","sev":"Info","cvss":"","host":"192.168.40.21","port":"8102","proto":"recon",
  "cat":"openport","mitre":"",
  "title":"Open port 8102/tcp — proprietary service",
  "raw":"Open Port 8102/tcp: kz-migr?",
  "desc":"Port 8102/tcp is open with an unidentified/proprietary banner. Unknown listening services warrant identification and access review.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"8102/tcp open  kz-migr?  [banner] \\x00\\x00\\x00\\xC8… 59386fd9c7a941738a793249941eebd",
  "fix":"Identify the service and owner; disable if unnecessary or restrict to management networks."},
 {"id":"F-33","sev":"Info","cvss":"","host":"192.168.40.3","port":"80","proto":"http",
  "cat":"connectfail","mitre":"",
  "title":"Endpoint unreachable during probe",
  "raw":"[FAIL] Unable to connect to 192.168.40.3:80.",
  "desc":"A probe to 192.168.40.3:80 failed to connect, indicating intermittent availability or filtering during the test window. Recorded as coverage evidence.",
  "basis":"Severity INFO as assessed by the finding producer from its collected evidence.",
  "evidence":"[FAIL] Unable to connect to 192.168.40.3:80.",
  "fix":"Confirm availability and whether a control blocked the probe; re-test to close coverage gaps."},
 {"id":"F-34","sev":"Info","cvss":"","host":"192.168.40.4","port":"","proto":"exploit",
  "cat":"accesscontrol","mitre":"",
  "title":"Access-controlled surface discovered",
  "raw":"Access-controlled surface discovered",
  "desc":"An endpoint responded with an authentication/authorization challenge, revealing a protected surface worth targeting with default-credential and auth-bypass checks.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"An endpoint responded with an authentication/authorisation challenge.",
  "fix":"Verify strong, unique credentials and MFA on the protected surface; review for auth-bypass and default accounts."},
 {"id":"F-35","sev":"Info","cvss":"","host":"192.168.40.4","port":"","proto":"recon",
  "cat":"addetect","mitre":"",
  "title":"Active Directory / SMB detected",
  "raw":"Active Directory / SMB detected",
  "desc":"Active Directory and SMB were identified by banner match. SMB (TCP 445) underpins most Windows lateral-movement paths and is a high-value target; historic CVEs make exposed, unsigned SMB especially risky.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"CVE references listed by the finding producer: CVE-2017-0144 (EternalBlue), CVE-2020-0796 (SMBGhost), CVE-2021-36942 (PetitPotam), CVE-2019-1040 (NTLM) · CISA KEV: CVE-2017-0144.",
  "fix":"Enforce SMB signing, disable SMBv1, restrict TCP 445 to required hosts, and confirm current patch level against the SMB/AD CVEs referenced above."},
 {"id":"F-36","sev":"Info","cvss":"","host":"192.168.40.4","port":"","proto":"recon",
  "cat":"dbdetect","mitre":"",
  "title":"Database services detected (MSSQL/MySQL/PG/Mongo/Redis)",
  "raw":"Databases (MSSQL/MySQL/PG/Mongo/Redis) detected",
  "desc":"Database services were identified by banner/marker match. On native ports (1433/3306/5432/27017/6379) these are high-value targets; default or blank credentials remain common and can lead directly to data exfiltration.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"CVE references listed by the finding producer (verbatim): CVE-2020-1472, CVE-2019-3822, CVE-2021-33026, CVE-2022-0543, CVE-2023-28879.",
  "fix":"Require authentication with strong unique credentials and bind databases to internal interfaces only. Note: the producer-listed CVEs above are mixed and mostly not database-specific (e.g. Zerologon is AD/Netlogon, CVE-2019-3822 is curl) — validate applicability before actioning rather than patching against the list as-is."},
 {"id":"F-37","sev":"Info","cvss":"","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"openport","mitre":"",
  "title":"Web crawl summary — 8641 requests, 5 items",
  "raw":"8641 requests: 0 errors and 5 items reported on the remote host",
  "desc":"Automated crawling issued 8,641 requests with 0 errors and reported 5 items on the host. Coverage/telemetry evidence for the web assessment.",
  "basis":"Severity INFO as assessed by the finding producer from its collected evidence.",
  "evidence":"8641 requests: 0 errors and 5 items reported on the remote host",
  "fix":"Informational. Review the 5 reported items alongside the web findings for this host."},
 {"id":"F-38","sev":"Info","cvss":"","host":"192.168.40.8","port":"80","proto":"recon",
  "cat":"serverdisclosure","mitre":"",
  "title":"Server banner disclosure — Crestron Webserver",
  "raw":"HTTP 80 — Server Disclosure: Crestron Webserver",
  "desc":"The HTTP service discloses “Crestron Webserver” in its banner. Version/product disclosure aids targeted attack selection against the AV/building-automation device.",
  "basis":"Attack-surface detection — present, not exploitable on its own.",
  "evidence":"HTTP/1.1 301 Moved Permanently\nLocation: https://192.168.40.8/index_banner.html\nX-Frame-Options: SAMEORIGIN",
  "fix":"Suppress or genericize the Server banner where supported; ensure the device runs current firmware and is network-segmented."},
 {"id":"F-39","sev":"Info","cvss":"","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"serverdisclosure","mitre":"",
  "title":"Platform disclosure — unknown",
  "raw":"Platform: Unknown",
  "desc":"The platform could not be positively fingerprinted; recorded for completeness.",
  "basis":"Severity INFO as assessed by the finding producer from its collected evidence.",
  "evidence":"Platform: Unknown",
  "fix":"Informational; no action required."},
 {"id":"F-40","sev":"Info","cvss":"","host":"192.168.40.8","port":"80","proto":"http",
  "cat":"serverdisclosure","mitre":"",
  "title":"Server header — Crestron Webserver",
  "raw":"Server: Crestron Webserver",
  "desc":"The Server response header identifies the product as “Crestron Webserver.”",
  "basis":"Severity INFO as assessed by the finding producer from its collected evidence.",
  "evidence":"Server: Crestron Webserver",
  "fix":"Suppress or genericize the Server header where the device supports it."},
]

# ---- Attack surface: services observed per host (compiled from recon findings) ----
ATTACK_SURFACE = [
    {"ip":"192.168.40.8","os":"Unknown","services":[
        {"port":"80","proto":"tcp","service":"http","product":"Crestron Webserver (301 → HTTPS)","risk":"high"},
    ]},
    {"ip":"192.168.40.4","os":"Windows / AD","services":[
        {"port":"23","proto":"tcp","service":"telnet","product":"Cleartext protocol · nmap-filtered","risk":"med"},
        {"port":"512","proto":"tcp","service":"exec (rexec)","product":"Cleartext r-service · nmap-filtered","risk":"med"},
        {"port":"513","proto":"tcp","service":"login (rsh)","product":"Cleartext r-service · nmap-filtered","risk":"med"},
        {"port":"514","proto":"tcp","service":"shell (rsh)","product":"Cleartext r-service · nmap-filtered","risk":"med"},
        {"port":"3389","proto":"tcp","service":"ms-wbt-server","product":"RDP — no NLA / weak encryption · filtered","risk":"med"},
        {"port":"443","proto":"tcp","service":"https","product":"Web — missing headers","risk":"low"},
        {"port":"80","proto":"tcp","service":"http","product":"Web — missing headers","risk":"low"},
        {"port":"8080","proto":"tcp","service":"http-alt","product":"Web — missing headers","risk":"low"},
        {"port":"8443","proto":"tcp","service":"https-alt","product":"Web — missing headers","risk":"low"},
        {"port":"8888","proto":"tcp","service":"http-alt","product":"Web — missing headers","risk":"low"},
        {"port":"445","proto":"tcp","service":"smb / AD","product":"Active Directory / SMB detected","risk":"info"},
        {"port":"—","proto":"tcp","service":"databases","product":"MSSQL/MySQL/PG/Mongo/Redis detected","risk":"info"},
    ]},
    {"ip":"192.168.40.21","os":"Linux","services":[
        {"port":"80","proto":"tcp","service":"http","product":"Embedded device UI","risk":"info"},
        {"port":"443","proto":"tcp","service":"ssl/https","product":"TLS service","risk":"info"},
        {"port":"554","proto":"tcp","service":"rtsp","product":"Hikvision (Digest auth)","risk":"info"},
        {"port":"8102","proto":"tcp","service":"kz-migr?","product":"Proprietary / unidentified","risk":"info"},
    ]},
    {"ip":"192.168.40.17","os":"Unknown","services":[
        {"port":"80","proto":"tcp","service":"http","product":"Web app (IDOR observed) · intermittent","risk":"med"},
    ]},
    {"ip":"192.168.40.3","os":"Unknown","services":[
        {"port":"80","proto":"tcp","service":"http","product":"Web app (IDOR observed) · intermittent","risk":"med"},
    ]},
    {"ip":"192.168.40.2","os":"Unknown","services":[
        {"port":"—","proto":"—","service":"no access","product":"No foothold obtained — coverage only","risk":"info"},
    ]},
]

# ---- Kill chain / attack path (ordered steps, as executed) ----
KILL_CHAIN = [
    {"n":1,"phase":"Recon","label":"Initial contact — 192.168.40.2","detail":"First target engaged; reconnaissance begins."},
    {"n":2,"phase":"Chain analysis","label":"Wildcard DNS *.192.168.40.2","detail":"Wildcard DNS resolution identified as a potential pivot."},
    {"n":3,"phase":"Chain analysis","label":"Subdomain takeover check","detail":"Assessed for dangling records / takeover potential."},
    {"n":4,"phase":"Chain analysis","label":"Phishing-domain setup path","detail":"Hypothesis retained; no action taken against out-of-scope users."},
    {"n":5,"phase":"Chain analysis","label":"Wildcard DNS → subdomain takeover","detail":"Chained hypothesis evaluated."},
    {"n":6,"phase":"Chain analysis","label":"Recon → internal pivot","detail":"Mapping toward internal host discovery."},
    {"n":7,"phase":"Chain analysis","label":"Internal host discovery","detail":"Adjacent hosts enumerated across the segment."},
    {"n":8,"phase":"Exploit","label":"Objective — no access","detail":"Engagement objective on 192.168.40.2 ended in NO_ACCESS."},
    {"n":9,"phase":"Recon","label":"Pivot to 192.168.40.3","detail":"Next target engaged."},
    {"n":10,"phase":"Chain analysis","label":"Wildcard DNS *.192.168.40.3","detail":"Wildcard DNS resolution identified."},
    {"n":11,"phase":"Chain analysis","label":"Subdomain takeover check","detail":"Assessed for takeover potential."},
    {"n":12,"phase":"Chain analysis","label":"Service discovery","detail":"Service enumeration across discovered hosts; deepest access reached remained NO_ACCESS."},
]
KILL_CHAIN_PHASES = ["Recon","Exploit / Foothold","Privilege Esc","Post-exploit / Loot","Persistence","Lateral"]

# ---- MITRE ATT&CK techniques observed ----
MITRE = [
    {"id":"T1059","name":"Command & Scripting Interpreter","tactic":"Execution","count":1,
     "findings":["F-09"],"detail":"OS command-injection signal on 192.168.40.8."},
    {"id":"T1059.007","name":"JavaScript (XSS)","tactic":"Execution","count":1,
     "findings":["F-11"],"detail":"Cross-site scripting flagged on 192.168.40.8."},
    {"id":"T1212","name":"Exploitation for Credential Access","tactic":"Credential Access","count":3,
     "findings":["F-02","F-03","F-10"],"detail":"IDOR / BOLA on 192.168.40.17, .3 and .8."},
    {"id":"T1040","name":"Network Sniffing","tactic":"Credential Access","count":4,
     "findings":["F-04","F-05","F-06","F-07"],"detail":"Cleartext Telnet/REXEC/RSH on 192.168.40.4."},
    {"id":"T1021.001","name":"Remote Services: RDP","tactic":"Lateral Movement","count":1,
     "findings":["F-08"],"detail":"RDP without NLA / weak encryption on 192.168.40.4."},
]

# ---- Blue-team detection opportunities (status OPEN for all, as reported) ----
DETECTION = [
    {"finding":"Missing X-Content-Type-Options header","tech":"—","host":"192.168.40.8"},
    {"finding":"IDOR / BOLA — unauthorized object access","tech":"T1212","host":"192.168.40.17"},
    {"finding":"IDOR / BOLA — unauthorized object access","tech":"T1212","host":"192.168.40.3"},
    {"finding":"Cleartext protocol — TELNET (23)","tech":"T1040","host":"192.168.40.4"},
    {"finding":"Cleartext protocol — REXEC (512)","tech":"T1040","host":"192.168.40.4"},
    {"finding":"Cleartext protocol — RSH (513)","tech":"T1040","host":"192.168.40.4"},
    {"finding":"Cleartext protocol — RSH (514)","tech":"T1040","host":"192.168.40.4"},
    {"finding":"RDP — no NLA / weak encryption","tech":"T1021.001","host":"192.168.40.4"},
    {"finding":"Command injection — likely RCE","tech":"T1059","host":"192.168.40.8"},
    {"finding":"IDOR / BOLA — unauthorized object access","tech":"T1212","host":"192.168.40.8"},
    {"finding":"XSS (nmap http-xssed)","tech":"T1059.007","host":"192.168.40.8"},
    {"finding":"Missing security headers (CSP / permissions / referrer / HSTS)","tech":"—","host":"multiple"},
    {"finding":"Server / platform disclosure — Crestron","tech":"—","host":"192.168.40.8"},
    {"finding":"Active Directory / SMB detected","tech":"—","host":"192.168.40.4"},
    {"finding":"Databases detected","tech":"—","host":"192.168.40.4"},
    {"finding":"Open ports — RTSP / HTTP / proprietary","tech":"—","host":"192.168.40.21"},
]

# ---- Remediation roadmap: consolidate 40 findings into prioritized workstreams ----
REMEDIATION = [
    {"rank":"P1","title":"Investigate & contain web injection on 192.168.40.8","priority":"Immediate",
     "impact":"High","effort":"Medium","owner":"AppSec + Host owner",
     "findings":["F-09","F-11"],
     "summary":"The OS command-injection indicator (F-09) on the Crestron web host is the highest-potential-impact issue and should be confirmed first — eliminate shell execution on user input, deploy an interim WAF virtual patch, and review logs for exploitation. Treat the flagged XSS (F-11) as unconfirmed: the archive lookup returned no match, so it needs manual verification of a real sink before remediation, not urgent patching.",
     "cats":["cmdinjection","xss"]},
    {"rank":"P2","title":"Remediate broken object-level authorization (IDOR/BOLA)","priority":"Immediate",
     "impact":"High","effort":"Medium","owner":"Application teams",
     "findings":["F-02","F-03","F-10"],
     "summary":"Three hosts expose objects (id=0) without authorization. Enforce deny-by-default, per-request object-level authorization and adopt unguessable identifiers across the affected applications.",
     "cats":["idor"]},
    {"rank":"P3","title":"Eliminate cleartext & weak remote-access protocols on 192.168.40.4","priority":"High",
     "impact":"High","effort":"Low","owner":"Infrastructure / Windows admins",
     "findings":["F-04","F-05","F-06","F-07","F-08"],
     "summary":"Disable Telnet and the r-services (512–514); move all admin access to SSH. Require NLA and strong TLS on RDP and restrict it to a jump host / VPN. Low effort, high risk reduction.",
     "cats":["cleartext","rdp"]},
    {"rank":"P4","title":"Deploy a baseline HTTP security-header standard everywhere","priority":"High",
     "impact":"Medium","effort":"Low","owner":"Platform / Web ops",
     "findings":["F-01","F-12","F-13","F-14","F-15","F-16","F-17","F-18","F-19","F-20","F-21","F-22","F-23","F-24","F-25"],
     "summary":"Fifteen findings (including the sole High) are missing-header hygiene across many endpoints. Standardize CSP, HSTS, X-Content-Type-Options, X-Frame-Options, Referrer-Policy and Permissions-Policy at the web/proxy tier and validate in CI. Single control, broad coverage.",
     "cats":["header"]},
    {"rank":"P5","title":"Harden exposed management, IoT & data services","priority":"Medium",
     "impact":"Medium","effort":"Medium","owner":"Infrastructure / Device owners",
     "findings":["F-30","F-31","F-32","F-34","F-35","F-36","F-38"],
     "summary":"Segment and restrict the Hikvision RTSP camera, the proprietary :8102 service, Active Directory/SMB and database services to trusted networks. Change default credentials, enforce SMB signing, and confirm firmware/patch levels against the referenced CVEs.",
     "cats":["openport","accesscontrol","addetect","dbdetect","serverdisclosure"]},
    {"rank":"P6","title":"Close coverage gaps & validate availability","priority":"Low",
     "impact":"Low","effort":"Low","owner":"IT operations",
     "findings":["F-26","F-33","F-27","F-28","F-29","F-37","F-39","F-40"],
     "summary":"Two endpoints were intermittently unreachable during testing; confirm availability and whether controls blocked probes, then re-test to close coverage gaps. Remaining items are informational recon/coverage evidence.",
     "cats":["connectfail","noaccess","osfingerprint"]},
]

# CVSS v3.1 severity bands (as stated by ARGUS)
CVSS_BANDS = [
    {"band":"9.0 – 10.0","sev":"Critical","desc":"Demonstrated compromise / catastrophic impact"},
    {"band":"7.0 – 8.9","sev":"High","desc":"Public exploit or confirmed direct exploitability"},
    {"band":"4.0 – 6.9","sev":"Medium","desc":"Confirmed, chainable weakness"},
    {"band":"0.1 – 3.9","sev":"Low","desc":"Minor issue / information leak"},
    {"band":"0.0","sev":"Info","desc":"Detection / attack surface"},
]

METHODOLOGY = [
    {"step":"Plan","body":"ARGUS builds a hypothesis tree of testable attack paths from reconnaissance, activating nodes as evidence accrues."},
    {"step":"Execute","body":"Ordered tool dispatch against each hypothesis; every action is logged with its command, raw output and MITRE ATT&CK annotation. Non-exploitable paths are retained as coverage evidence."},
    {"step":"Validate","body":"A finding is published only when it passes the Issue-Validator gate — grounded in concrete tool output, accurately CVSS-scored, with reproduction recorded. Unsubstantiated claims are demoted, not shipped."},
]
